name: Check EasyConnect versions

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      different: {{ steps.compare.outputs.different }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compare pkg_version.xml
        id: compare
        run: |
          wget http://download.sangfor.com.cn/download/product/sslvpn/pkg/pkg_version.xml -O pkg_version_remote.xml
          if diff pkg_version.xml pkg_version_remote.xml >/dev/null; then
            echo "different=false" >> $GITHUB_OUTPUT
          else
            echo "different=true" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Replace pkg_version.xml
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          cp pkg_version_remote.xml pkg_version.xml
          git add pkg_version.xml
          git commit -m "Update pkg_version.xml"
          git push
        if: steps.compare.outputs.different == 'true'

  rebuild:
    uses: ./.github/workflows/build-and-push-docker-image.yml
    secrets: inherit
    needs: check
    if: needs.check.outputs.different == 'true'
